spring.application.name=car-sharing-app
spring.datasource.url=jdbc:postgresql://localhost:3009/car_sharing_db
spring.datasource.username=postgres
spring.datasource.password=movazot7a8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.enabled=false
server.port=8088
